const states = [
    'Acre',
    'Alagoas',
    'Amapá',
    'Amazonas',
    'Bahia',
    'Ceará',
    'Distrito Federal',
    'Espírito Santo',
    'Goiás',
    'Paraná',
    'Mato Grosso',
    'Mato Grosso do Sul',
    'Maranhão',
    'Minas Gerais',
    'Pará',
    'Paraíba',
    'Pernambuco',
    'Piauí',
    'Rio de Jabeiro',
    'Rio Grande do Norte',
    'Rio Grande do Sul',
    'Rondônia',
    'Roraima',
    'Santa Catarina',
    'São Paulo',
    'Sergipe',
    'Tocantins',
]

export default states